// Generated by CoffeeScript 1.11.1
(function() {
  var arr, i, isRight, item, len, myfunc, myfunc2, num, obj, ref, result, str;

  num = 10;

  console.log(num);

  obj = {
    a: 13,
    b: 'abc',
    fun: function() {
      return this.a;
    }
  };

  myfunc = function() {
    num += 5;
    console.log("函数:" + obj.a);
    return console.log("函数:" + obj.fun());
  };

  result = myfunc();

  console.log(result);

  myfunc2 = function(name, age) {
    if (age == null) {
      age = 20;
    }
    return console.log(name + " " + age);
  };

  myfunc2('tom');

  str = 'abc';

  isRight = true;

  if (isRight) {
    str += '123';
  }

  console.log(str);

  if (str === 'abc') {
    str += '123';
  } else {
    str += 'abc';
  }

  console.log(str);

    if ((ref = str === 'abc') != null) {
    ref;
  } else {
    str += {
      '123': str += 'abc'
    };
  };

  console.log(str);

  arr = [1, 21, 15, 3, 11, 5, 3];

  for (i = 0, len = arr.length; i < len; i++) {
    item = arr[i];
    if ((0 < item && item < 10)) {
      console.log(item);
    }
  }

}).call(this);

//# sourceMappingURL=mytest.js.map
