// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/login', {
        templateUrl: '/app/login/login.html',
        controller: 'LoginCtrl'
      }).when('/regist', {
        templateUrl: '/app/regist/reg.html',
        controller: 'registCtrl'
      }).when('/', {
        templateUrl: '/app/index/index.html',
        controller: 'indexCtrl'
      });
    }
  ]).run([
    '$location', function($location) {
      return $location.path('/login').replace();
    }
  ]);

}).call(this);

//# sourceMappingURL=index.js.map
