// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('indexCtrl', [
    '$scope', function($scope) {
      console.log('进入主页');
      $scope.task = {
        description: '',
        checked: false
      };
      $scope.taskList = [];
      $scope.addTask = function() {
        var task;
        console.log($scope.task);
        task = angular.copy($scope.task);
        task.checked = false;
        $scope.taskList.push(task);
        $scope.task.description = '';
      };
      return 1;
    }
  ]);

}).call(this);

//# sourceMappingURL=indexCtrl.js.map
