// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('registCtrl', [
    '$scope', function($scope) {
      $scope.userEntity = {
        username: '',
        password: '',
        password2: ''
      };
      return $scope.doReg = function() {
        return console.log($scope.userEntity);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registCtrl.js.map
