// Generated by CoffeeScript 1.11.1
(function() {
  angular.module('tmsApp').controller('LoginCtrl', [
    '$scope', '$location', function($scope, $location) {
      $scope.userEntity = {
        username: '',
        password: ''
      };
      $scope.rememberMe = false;
      return $scope.doLogin = function() {
        console.log($scope.userEntity);
        $location.path('/').replace;
        return console.log($scope.rememberMe);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=LoginCtrl.js.map
